name: Upload Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4 # or your Ruby version

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll Site
      run: bundle exec jekyll build

    - name: Optimize CSS with PurgeCSS
      run: |
        npm install -g purgecss
        purgecss -c purgecss.config.js

    - name: Upload to S3 and Invalidate CloudFront Cache
      uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
        AWS_REGION: 'ap-south-1'              # change if needed
        SOURCE_DIR: '_site'                   # Jekyll output
        DEST_DIR: ''                          # upload to root of bucket
